### ISSUE TITLE
Profiling crashes when run using JAX

### ISSUE THREAD

**Issue by tbaker2** [openxla/xla#4431] opened 2023-07-21 22:25 UTC
Setting the xla_hlo_profile flag causes JAX programs to crash when running on a CPU. This program results in a segmentation fault on line 4.
```
import os
os.environ['XLA_FLAGS'] = "--xla_hlo_profile"
import jax.numpy as jnp
input = jnp.arange(10) 
```

Here is the output:
```
No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
Segmentation fault (core dumped)
```

XLA does pass '//xla/tests:xla_hlo_profile_test_cpu'

**Comment by cheshire** [comment] 2023-07-22 10:08
@sherhut any pointers?

**Comment by cheshire** [comment] 2023-07-23 07:39
Not sure if that flag is supported on CPUs, but either way it definitely should not crash.

**Comment by sherhut** [comment] 2023-07-24 10:20
@d0k do you know? Otherwise, maybe @penpornk can take a look.

**Comment by d0k** [comment] 2023-07-24 11:04
It's not supported. It's a very limited profiling tool that works by instrumenting ops and writing cycle counts into a profile counter buffer. I think JAX never sets up that buffer.

It might be possible to port the code to set up the profile counter buffer from TF to JAX, but using a sampling profiler like perf or vTune likely gives you better results (it's hard to match back instructions to HLO though).

**Comment by tbaker2** [comment] 2023-07-24 18:01
> It's not supported. It's a very limited profiling tool that works by instrumenting ops and writing cycle counts into a profile counter buffer. I think JAX never sets up that buffer.

Why would JAX set up a buffer? It is an XLA flag. It should all be internal to XLA.

> 
> It might be possible to port the code to set up the profile counter buffer from TF to JAX, but using a sampling profiler like perf or vTune likely gives you better results (it's hard to match back instructions to HLO though).

I have tried to use vtune. The problem is much of the time reported is inside the thread pool WorkerLoop. There is no information about what operations are being run in the threads.

**Comment by d0k** [comment] 2023-07-27 08:41
> > It's not supported. It's a very limited profiling tool that works by instrumenting ops and writing cycle counts into a profile counter buffer. I think JAX never sets up that buffer.
> 
> Why would JAX set up a buffer? It is an XLA flag. It should all be internal to XLA.

It is, but JAX (pjrt) calls into the compiled code with a function pointer and that's where the profile counter buffer has to be passed along. As far as I can see that is missing and it always passes nullptr.

> 
> > It might be possible to port the code to set up the profile counter buffer from TF to JAX, but using a sampling profiler like perf or vTune likely gives you better results (it's hard to match back instructions to HLO though).
> 
> I have tried to use vtune. The problem is much of the time reported is inside the thread pool WorkerLoop. There is no information about what operations are being run in the threads.

True, I've been piecing stuff together from the disassembly which is a rather tedious process.

**Comment by tbaker2** [comment] 2023-07-27 18:00
> It is, but JAX (pjrt) calls into the compiled code with a function pointer and that's where the profile counter buffer has to be passed along. As far as I can see that is missing and it always passes nullptr.
> 
That is not what I see. For the trivial example above, the crash happens in the XLA code [here](https://github.com/openxla/xla/blob/e68777ca34e99192d1d52ea087c5e119f8525f8b/xla/pjrt/tfrt_cpu_pjrt_client.cc#L1312). According to the function [type ](https://github.com/openxla/xla/blob/e68777ca34e99192d1d52ea087c5e119f8525f8b/xla/service/cpu/cpu_executable.h#L196) the last parameter is a pointer to array of ints. A nullptr constant is passed into the function. So even if JAX did pass in a buffer it wouldn't make it through.

The test case will run when I pass an array of ints into the compute_function. Of course, there is nowhere to put the results. For a slightly less trivial test case that actually executes an operation a crash happens [here](https://github.com/openxla/xla/blob/e68777ca34e99192d1d52ea087c5e119f8525f8b/xla/pjrt/tfrt_cpu_pjrt_client.cc#L1377) which is the same call.

**Comment by christianjgreen** [comment] 2024-06-06 23:54
> > It is, but JAX (pjrt) calls into the compiled code with a function pointer and that's where the profile counter buffer has to be passed along. As far as I can see that is missing and it always passes nullptr.
> 
> That is not what I see. For the trivial example above, the crash happens in the XLA code [here](https://github.com/openxla/xla/blob/e68777ca34e99192d1d52ea087c5e119f8525f8b/xla/pjrt/tfrt_cpu_pjrt_client.cc#L1312). According to the function [type ](https://github.com/openxla/xla/blob/e68777ca34e99192d1d52ea087c5e119f8525f8b/xla/service/cpu/cpu_executable.h#L196) the last parameter is a pointer to array of ints. A nullptr constant is passed into the function. So even if JAX did pass in a buffer it wouldn't make it through.
> 
> The test case will run when I pass an array of ints into the compute_function. Of course, there is nowhere to put the results. For a slightly less trivial test case that actually executes an operation a crash happens [here](https://github.com/openxla/xla/blob/e68777ca34e99192d1d52ea087c5e119f8525f8b/xla/pjrt/tfrt_cpu_pjrt_client.cc#L1377) which is the same call.

Do you currently have any work around for profiling the code?

**Comment by tvladyslav** [comment] 2024-12-09 18:23
I was not able to reproduce the crash.
Due to profiling, old runtime never had it working well. As far as we are migrating to the new runtime, there is no point in fixing it there.
At the same time, profiling in the new (thunks) runtime is not yet implemented.

Closing ticket as "won't fix".

**Closed by tvladyslav** 2024-12-09 18:23 UTC
Labels: bug, CPU
