### ISSUE TITLE
There is a compilation error and its modification.

### ISSUE THREAD

**Issue by ckfgihub** [openxla/xla#5790] opened 2023-09-21 11:16 UTC
/service/_objs/hlo_graph_dumper/hlo_graph_dumper.o:hlo_graph_dumper.cc:function xla::(anonymous namespace)::HloDotDumper::GetInstructionNodeBackendConfig(xla::HloInstruction const*): error: undefined reference to 'stream_executor::dnn::ActivationModeStringabi:cxx11'

must modify ：
diff --git a/xla/service/BUILD b/xla/service/BUILD
index 9ee93c595..688b3b38e 100644
--- a/xla/service/BUILD
+++ b/xla/service/BUILD
@@ -5108,6 +5108,7 @@ cc_library(
         "//xla:xla_proto_cc",
         "//xla/hlo/ir:hlo",
         "//xla/service/gpu:backend_configs_cc",
+        "//xla/stream_executor:dnn",
         "//xla/service/gpu:cublas_cudnn",
         "//xla/stream_executor:stream_executor_headers",
         "@com_google_absl//absl/container:flat_hash_map",

**Comment by ezhulenev** [comment] 2023-09-22 23:00
I pushed a fix yesterday, can you check if it fixed your issue.

**Comment by penpornk** [comment] 2024-02-29 04:45
Since this issue has been inactive in the past 5 months, I'll assume the issue is gone with @ezhulenev's fix and will close the issue. Please feel free to reopen it if this is not the case.

**Closed by penpornk** 2024-02-29 04:45 UTC
