### ISSUE TITLE
Compiling xla/mlir/tools/mlir_interpreter/dialects/util.cc failed

### ISSUE THREAD

**Issue by dulingkang** [openxla/xla#12559] opened 2024-05-16 09:37 UTC
compile command: 
```
./configure.py --backend=CUDA
bazel build --test_output=all --spawn_strategy=sandboxed //xla/... --python_path=/usr/bin/python3.9 --sandbox_debug
```
error compile log:
```
xla/xla/mlir/tools/mlir_interpreter/dialects/BUILD:46:11: Compiling xla/mlir/tools/mlir_interpreter/dialects/util.cc failed: (Exit 1): linux-sandbox failed: error executing command 
  (cd /home/dss/.cache/bazel/_bazel_dss/4bc65a6054bf39baecdeb1fdf79bd001/sandbox/linux-sandbox/10908/execroot/xla && \
  exec env - \
    LD_LIBRARY_PATH=/usr/local/cuda/lib64:/usr/local/cuda/lib64: \
    PATH=/usr/local/cuda/bin:/usr/local/cuda/bin:/home/dss/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin \
    PWD=/proc/self/cwd \
    TF2_BEHAVIOR=1 \
    TMPDIR=/tmp \
  /home/dss/.cache/bazel/_bazel_dss/install/20da5ab742b8d3d499c34fdafcd3c8b8/linux-sandbox -t 15 -w /home/dss/.cache/bazel/_bazel_dss/4bc65a6054bf39baecdeb1fdf79bd001/sandbox/linux-sandbox/10908/execroot/xla -w /tmp -w /dev/shm -S /home/dss/.cache/bazel/_bazel_dss/4bc65a6054bf39baecdeb1fdf79bd001/sandbox/linux-sandbox/10908/stats.out -D -- /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-std=c++14' -MD -MF bazel-out/k8-opt/bin/xla/mlir/tools/mlir_interpreter/dialects/_objs/dialect_utils/util.pic.d '-frandom-seed=bazel-out/k8-opt/bin/xla/mlir/tools/mlir_interpreter/dialects/_objs/dialect_utils/util.pic.o' -fPIC '-DLLVM_ON_UNIX=1' '-DHAVE_BACKTRACE=1' '-DBACKTRACE_HEADER=<execinfo.h>' '-DLTDL_SHLIB_EXT=".so"' '-DLLVM_PLUGIN_EXT=".so"' '-DLLVM_ENABLE_THREADS=1' '-DHAVE_DEREGISTER_FRAME=1' '-DHAVE_LIBPTHREAD=1' '-DHAVE_PTHREAD_GETNAME_NP=1' '-DHAVE_PTHREAD_H=1' '-DHAVE_PTHREAD_SETNAME_NP=1' '-DHAVE_REGISTER_FRAME=1' '-DHAVE_SETENV_R=1' '-DHAVE_STRERROR_R=1' '-DHAVE_SYSEXITS_H=1' '-DHAVE_UNISTD_H=1' -D_GNU_SOURCE '-DHAVE_LINK_H=1' '-DHAVE_MALLINFO=1' '-DHAVE_SBRK=1' '-DHAVE_STRUCT_STAT_ST_MTIM_TV_NSEC=1' -DHAVE_BUILTIN_THREAD_POINTER '-DLLVM_NATIVE_ARCH="X86"' '-DLLVM_NATIVE_ASMPARSER=LLVMInitializeX86AsmParser' '-DLLVM_NATIVE_ASMPRINTER=LLVMInitializeX86AsmPrinter' '-DLLVM_NATIVE_DISASSEMBLER=LLVMInitializeX86Disassembler' '-DLLVM_NATIVE_TARGET=LLVMInitializeX86Target' '-DLLVM_NATIVE_TARGETINFO=LLVMInitializeX86TargetInfo' '-DLLVM_NATIVE_TARGETMC=LLVMInitializeX86TargetMC' '-DLLVM_NATIVE_TARGETMCA=LLVMInitializeX86TargetMCA' '-DLLVM_HOST_TRIPLE="x86_64-unknown-linux-gnu"' '-DLLVM_DEFAULT_TARGET_TRIPLE="x86_64-unknown-linux-gnu"' '-DLLVM_VERSION_MAJOR=19' '-DLLVM_VERSION_MINOR=0' '-DLLVM_VERSION_PATCH=0' '-DLLVM_VERSION_STRING="19.0.0git"' -D__STDC_LIMIT_MACROS -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS '-DBLAKE3_USE_NEON=0' -DBLAKE3_NO_AVX2 -DBLAKE3_NO_AVX512 -DBLAKE3_NO_SSE2 -DBLAKE3_NO_SSE41 '-DBAZEL_CURRENT_REPOSITORY=""' -iquote . -iquote bazel-out/k8-opt/bin -iquote external/com_google_absl -iquote bazel-out/k8-opt/bin/external/com_google_absl -iquote external/llvm-project -iquote bazel-out/k8-opt/bin/external/llvm-project -isystem external/llvm-project/llvm/include -isystem bazel-out/k8-opt/bin/external/llvm-project/llvm/include -isystem external/llvm-project/mlir/include -isystem bazel-out/k8-opt/bin/external/llvm-project/mlir/include -Wno-all -Wno-extra -Wno-deprecated -Wno-deprecated-declarations -Wno-ignored-attributes -Wno-array-bounds -Wunused-result '-Werror=unused-result' -Wswitch '-Werror=switch' '-Wno-error=unused-but-set-variable' -DAUTOLOAD_DYNAMIC_KERNELS '-std=c++17' -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c xla/mlir/tools/mlir_interpreter/dialects/util.cc -o bazel-out/k8-opt/bin/xla/mlir/tools/mlir_interpreter/dialects/_objs/dialect_utils/util.pic.o)
1715851678.556162815: src/main/tools/linux-sandbox.cc:152: calling pipe(2)...
1715851678.556212133: src/main/tools/linux-sandbox.cc:171: calling clone(2)...
1715851678.556467489: src/main/tools/linux-sandbox.cc:180: linux-sandbox-pid1 has PID 1358660
1715851678.556515103: src/main/tools/linux-sandbox-pid1.cc:681: Pid1Main started
1715851678.556571244: src/main/tools/linux-sandbox.cc:197: done manipulating pipes
1715851678.556711901: src/main/tools/linux-sandbox-pid1.cc:285: working dir: /home/dss/.cache/bazel/_bazel_dss/4bc65a6054bf39baecdeb1fdf79bd001/sandbox/linux-sandbox/10908/execroot/xla
1715851678.556728522: src/main/tools/linux-sandbox-pid1.cc:320: writable: /home/dss/.cache/bazel/_bazel_dss/4bc65a6054bf39baecdeb1fdf79bd001/sandbox/linux-sandbox/10908/execroot/xla
1715851678.556735057: src/main/tools/linux-sandbox-pid1.cc:320: writable: /tmp
1715851678.556742385: src/main/tools/linux-sandbox-pid1.cc:320: writable: /dev/shm
1715851678.556796157: src/main/tools/linux-sandbox-pid1.cc:400: remount ro: /
1715851678.556803429: src/main/tools/linux-sandbox-pid1.cc:400: remount ro: /dev
1715851678.556807373: src/main/tools/linux-sandbox-pid1.cc:400: remount ro: /dev/pts
1715851678.556811689: src/main/tools/linux-sandbox-pid1.cc:400: remount rw: /dev/shm
1715851678.556814977: src/main/tools/linux-sandbox-pid1.cc:400: remount ro: /dev/mqueue
1715851678.556818420: src/main/tools/linux-sandbox-pid1.cc:400: remount ro: /dev/hugepages
1715851678.556822144: src/main/tools/linux-sandbox-pid1.cc:400: remount ro: /run
1715851678.556825511: src/main/tools/linux-sandbox-pid1.cc:400: remount ro: /run/lock
1715851678.556829431: src/main/tools/linux-sandbox-pid1.cc:400: remount ro: /run/user/1000
1715851678.556833531: src/main/tools/linux-sandbox-pid1.cc:400: remount ro: /run/user/1000/gvfs
1715851678.556838431: src/main/tools/linux-sandbox-pid1.cc:400: remount ro: /run/user/1000/doc
1715851678.556842288: src/main/tools/linux-sandbox-pid1.cc:400: remount ro: /run/user/126
1715851678.556846231: src/main/tools/linux-sandbox-pid1.cc:400: remount ro: /sys
1715851678.556877027: src/main/tools/linux-sandbox-pid1.cc:400: remount ro: /sys/kernel/security
1715851678.556885581: src/main/tools/linux-sandbox-pid1.cc:400: remount ro: /sys/fs/cgroup
1715851678.556890501: src/main/tools/linux-sandbox-pid1.cc:400: remount ro: /sys/fs/cgroup/unified
1715851678.556895206: src/main/tools/linux-sandbox-pid1.cc:400: remount ro: /sys/fs/cgroup/systemd
1715851678.556899138: src/main/tools/linux-sandbox-pid1.cc:400: remount ro: /sys/fs/cgroup/misc
1715851678.556903024: src/main/tools/linux-sandbox-pid1.cc:400: remount ro: /sys/fs/cgroup/blkio
1715851678.556906748: src/main/tools/linux-sandbox-pid1.cc:400: remount ro: /sys/fs/cgroup/memory
1715851678.556910698: src/main/tools/linux-sandbox-pid1.cc:400: remount ro: /sys/fs/cgroup/perf_event
1715851678.556914632: src/main/tools/linux-sandbox-pid1.cc:400: remount ro: /sys/fs/cgroup/net_cls,net_prio
1715851678.556918388: src/main/tools/linux-sandbox-pid1.cc:400: remount ro: /sys/fs/cgroup/cpu,cpuacct
1715851678.556922076: src/main/tools/linux-sandbox-pid1.cc:400: remount ro: /sys/fs/cgroup/hugetlb
1715851678.556925710: src/main/tools/linux-sandbox-pid1.cc:400: remount ro: /sys/fs/cgroup/pids
1715851678.556953287: src/main/tools/linux-sandbox-pid1.cc:400: remount ro: /sys/fs/cgroup/devices
1715851678.556957705: src/main/tools/linux-sandbox-pid1.cc:400: remount ro: /sys/fs/cgroup/freezer
1715851678.556961675: src/main/tools/linux-sandbox-pid1.cc:400: remount ro: /sys/fs/cgroup/cpuset
1715851678.556965081: src/main/tools/linux-sandbox-pid1.cc:400: remount ro: /sys/fs/cgroup/rdma
1715851678.556968927: src/main/tools/linux-sandbox-pid1.cc:400: remount ro: /sys/fs/pstore
1715851678.556972699: src/main/tools/linux-sandbox-pid1.cc:400: remount ro: /sys/firmware/efi/efivars
1715851678.556978188: src/main/tools/linux-sandbox-pid1.cc:400: remount ro: /sys/fs/bpf
1715851678.556981715: src/main/tools/linux-sandbox-pid1.cc:400: remount ro: /sys/kernel/debug
1715851678.556985804: src/main/tools/linux-sandbox-pid1.cc:400: remount ro: /sys/kernel/tracing
1715851678.556994695: src/main/tools/linux-sandbox-pid1.cc:400: remount ro: /sys/fs/fuse/connections
1715851678.557000106: src/main/tools/linux-sandbox-pid1.cc:400: remount ro: /sys/kernel/config
1715851678.557003548: src/main/tools/linux-sandbox-pid1.cc:400: remount ro: /proc
1715851678.557007095: src/main/tools/linux-sandbox-pid1.cc:400: remount ro: /proc/sys/fs/binfmt_misc
1715851678.557013295: src/main/tools/linux-sandbox-pid1.cc:422: remount(nullptr, /proc/sys/fs/binfmt_misc, nullptr, 2101281, nullptr) failure (Operation not permitted) ignored
1715851678.557040805: src/main/tools/linux-sandbox-pid1.cc:400: remount ro: /proc/sys/fs/binfmt_misc
1715851678.557045869: src/main/tools/linux-sandbox-pid1.cc:400: remount ro: /snap/bare/5
1715851678.557049590: src/main/tools/linux-sandbox-pid1.cc:400: remount ro: /snap/core20/2264
1715851678.557052623: src/main/tools/linux-sandbox-pid1.cc:400: remount ro: /snap/core22/1122
1715851678.557056099: src/main/tools/linux-sandbox-pid1.cc:400: remount ro: /snap/gnome-3-38-2004/119
1715851678.557059461: src/main/tools/linux-sandbox-pid1.cc:400: remount ro: /snap/core22/1380
1715851678.557062763: src/main/tools/linux-sandbox-pid1.cc:400: remount ro: /snap/gtk-common-themes/1535
1715851678.557066311: src/main/tools/linux-sandbox-pid1.cc:400: remount ro: /snap/gnome-42-2204/172
1715851678.557069928: src/main/tools/linux-sandbox-pid1.cc:400: remount ro: /snap/snapd/21184
1715851678.557072938: src/main/tools/linux-sandbox-pid1.cc:400: remount ro: /snap/snap-store/959
1715851678.557076112: src/main/tools/linux-sandbox-pid1.cc:400: remount ro: /snap/gnome-42-2204/176
1715851678.557079420: src/main/tools/linux-sandbox-pid1.cc:400: remount ro: /snap/gnome-3-38-2004/143
1715851678.557082960: src/main/tools/linux-sandbox-pid1.cc:400: remount ro: /snap/snapd/21465
1715851678.557099020: src/main/tools/linux-sandbox-pid1.cc:400: remount ro: /snap/snap-store/1113
1715851678.557103624: src/main/tools/linux-sandbox-pid1.cc:400: remount ro: /boot/efi
1715851678.557107696: src/main/tools/linux-sandbox-pid1.cc:400: remount ro: /snap/core20/2318
1715851678.557111020: src/main/tools/linux-sandbox-pid1.cc:400: remount ro: /tmp/fuse
1715851678.557114583: src/main/tools/linux-sandbox-pid1.cc:400: remount rw: /home/dss/.cache/bazel/_bazel_dss/4bc65a6054bf39baecdeb1fdf79bd001/sandbox/linux-sandbox/10908/execroot/xla
1715851678.557118703: src/main/tools/linux-sandbox-pid1.cc:400: remount rw: /home/dss/.cache/bazel/_bazel_dss/4bc65a6054bf39baecdeb1fdf79bd001/sandbox/linux-sandbox/10908/execroot/xla
1715851678.557122092: src/main/tools/linux-sandbox-pid1.cc:400: remount rw: /tmp
1715851678.557124778: src/main/tools/linux-sandbox-pid1.cc:400: remount ro: /tmp/fuse
1715851678.557128011: src/main/tools/linux-sandbox-pid1.cc:400: remount rw: /dev/shm
1715851678.557172876: src/main/tools/linux-sandbox-pid1.cc:491: calling fork...
1715851678.557318341: src/main/tools/linux-sandbox-pid1.cc:521: child started with PID 2
In file included from ./xla/mlir/tools/mlir_interpreter/framework/interpreter.h:29,
                 from ./xla/mlir/tools/mlir_interpreter/dialects/util.h:27,
                 from xla/mlir/tools/mlir_interpreter/dialects/util.cc:16:
./xla/mlir/tools/mlir_interpreter/framework/interpreter_value.h:102:27: error: declaration of 'std::shared_ptr<mlir::interpreter::Buffer> mlir::interpreter::InterpreterValue::Buffer() const' changes meaning of 'Buffer' [-fpermissive]
  102 |   std::shared_ptr<Buffer> Buffer() const;
      |                           ^~~~~~
In file included from ./xla/mlir/tools/mlir_interpreter/framework/interpreter_value.h:35,
                 from ./xla/mlir/tools/mlir_interpreter/framework/interpreter.h:29,
                 from ./xla/mlir/tools/mlir_interpreter/dialects/util.h:27,
                 from xla/mlir/tools/mlir_interpreter/dialects/util.cc:16:
./xla/mlir/tools/mlir_interpreter/framework/tensor_or_memref.h:190:7: note: 'Buffer' declared here as 'class mlir::interpreter::Buffer'
  190 | class Buffer {
      |       ^~~~~~
1715851684.029813423: src/main/tools/linux-sandbox-pid1.cc:538: wait returned pid=2, status=0x100
1715851684.029845234: src/main/tools/linux-sandbox-pid1.cc:556: child exited normally with code 1
1715851684.030359685: src/main/tools/linux-sandbox.cc:233: child exited normally with code 1
INFO: Elapsed time: 101.936s, Critical Path: 32.82s
INFO: 532 processes: 65 internal, 467 linux-sandbox.
FAILED: Build did NOT complete successfully
```

**Comment by reedwm** [comment] 2024-05-20 23:25
Note that I don't think building `//xla/...` is intended to work. Ideally it should, but I think we have many build targets that are either broken and unused, or only used in certain configurations that fail to build in other configurations.

That said, the error is in `interpreter_value.h`, which is used. I cannot reproduce the error though by running the build rule which builds this file. @dulingkang what compiler are you using? The following ran for me with clang-17 and CUDA 12.4.1

```
./configure.py --backend=CUDA
bazel build //xla/mlir/tools/mlir_interpreter/dialects
```

@jreiffers, probably best to avoid using the same name `Buffer` for a class and method name, given that this is failing on some compiler.

**Comment by dulingkang** [comment] 2024-05-22 06:46
> Note that I don't think building `//xla/...` is intended to work. Ideally it should, but I think we have many build targets that are either broken and unused, or only used in certain configurations that fail to build in other configurations.
> 
> That said, the error is in `interpreter_value.h`, which is used. I cannot reproduce the error though by running the build rule which builds this file. @dulingkang what compiler are you using? The following ran for me with clang-17 and CUDA 12.4.1
> 
> ```
> ./configure.py --backend=CUDA
> bazel build //xla/mlir/tools/mlir_interpreter/dialects
> ```
> 
> @jreiffers, probably best to avoid using the same name `Buffer` for a class and method name, given that this is failing on some compiler.
I used clang-17: 
```
INFO:root:Trying to find path to clang...
INFO:root:Found path to clang at /usr/lib/llvm-17/bin/clang
INFO:root:Running echo __clang_major__ | /usr/lib/llvm-17/bin/clang -E -P -
INFO:root:/usr/lib/llvm-17/bin/clang reports major version 17.
```

**Comment by jreiffers** [comment] 2024-05-22 06:54
@dulingkang Thanks for the report. This was yesterday fixed in https://github.com/openxla/xla/commit/8acce0832e9c99483232f80d7212b9e74b795fe1.

**Closed** 2024-05-22 10:29 UTC
