### ISSUE TITLE
Getting 'INTERNAL: cublasLtMatmul' error when using FP8

### ISSUE THREAD

**Issue by kaixih** [openxla/xla#6370] opened 2023-10-17 00:26 UTC
While testing the FP8 performance, we came across a specific error as below. The bisect analysis pointed to [this commit](https://github.com/openxla/xla/commit/f459e5777b49d5c34f4b27731fb1647728b5584a) as the cause. Upon reverting this commit, the error disappeared. @reedwm, have you heard anything about this commit?

@philipphack @wenscarl, if possible, could we create a unit test to catch similar errors in the future at an earlier stage?

```
023-10-16 13:55:17.319037: E external/xla/xla/pjrt/pjrt_stream_executor_client.cc:2716] Execution of replica 0 failed: INTERNAL: cublasLtMatmul( blas_lt_ref_.blas_lt_.get(), op_desc_.get(), alpha, a.opaque(), a_desc_.get(), b.opaque(), b_desc_.get(), beta, c.opaque(), c_desc_.get(), d.opaque(), d_desc_.get(), palgo, workspace, algorithm.workspace_size, gpu::AsGpuStreamValue(stream)): the requested functionality is not supported
2023-10-16 13:55:27.319266: F external/xla/xla/pjrt/pjrt_stream_executor_client.cc:2862] Replicated computation launch failed, but not all replicas terminated. Aborting process to work around deadlock. Failure message (there may have been multiple failures, see the error log for all failures): 

cublasLtMatmul( blas_lt_ref_.blas_lt_.get(), op_desc_.get(), alpha, a.opaque(), a_desc_.get(), b.opaque(), b_desc_.get(), beta, c.opaque(), c_desc_.get(), d.opaque(), d_desc_.get(), palgo, workspace, algorithm.workspace_size, gpu::AsGpuStreamValue(stream)): the requested functionality is not supported
Fatal Python error: Aborted

Current thread 0x00007ffff6d7d940 (most recent call first):
  File "/jt/jax/jax/_src/interpreters/pxla.py", line 1152 in __call__
  File "/jt/jax/jax/_src/profiler.py", line 340 in wrapper
  File "/jt/jax/jax/_src/pjit.py", line 1152 in _pjit_call_impl_python
  File "/jt/jax/jax/_src/pjit.py", line 1196 in call_impl_cache_miss
  File "/jt/jax/jax/_src/pjit.py", line 1212 in _pjit_call_impl
  File "/jt/jax/jax/_src/core.py", line 868 in process_primitive
  File "/jt/jax/jax/_src/core.py", line 388 in bind_with_trace
  File "/jt/jax/jax/_src/core.py", line 2656 in bind
  File "/jt/jax/jax/_src/pjit.py", line 167 in _python_pjit_helper
  File "/jt/jax/jax/_src/pjit.py", line 256 in cache_miss
  File "/jt/jax/jax/_src/traceback_util.py", line 177 in reraise_with_filtered_traceback
  File "/opt/paxml/paxml/trainer_lib.py", line 1692 in call
  File "/opt/paxml/paxml/programs.py", line 626 in train_step
  File "/opt/paxml/paxml/programs.py", line 337 in run
  File "/opt/praxis/praxis/py_utils.py", line 1023 in wrapper
  File "/opt/paxml/paxml/executors.py", line 406 in _train_and_evaluate_common
  File "/opt/paxml/paxml/executors.py", line 269 in start
  File "/opt/paxml/paxml/train.py", line 278 in train_and_evaluate
  File "/opt/praxis/praxis/py_utils.py", line 1023 in wrapper
  File "/opt/paxml/paxml/main.py", line 291 in run_experiment
  File "/opt/praxis/praxis/py_utils.py", line 1023 in wrapper
  File "/opt/paxml/paxml/main.py", line 427 in run
  File "/opt/praxis/praxis/py_utils.py", line 1023 in wrapper
  File "/opt/paxml/paxml/main.py", line 494 in _main
  File "/opt/praxis/praxis/py_utils.py", line 1023 in wrapper
  File "/opt/paxml/paxml/main.py", line 452 in main
  File "/usr/local/lib/python3.10/dist-packages/absl/app.py", line 254 in _run_main
  File "/usr/local/lib/python3.10/dist-packages/absl/app.py", line 308 in run
  File "/opt/paxml/paxml/main.py", line 517 in <module>

```

**Comment by reedwm** [comment] 2023-10-17 00:42
Not sure what the commit does. @akuegel any ideas how the commit could cause an error?

@kaixih if you share the HLO I can debug this if you'd like.

**Comment by kaixih** [comment] 2023-10-17 05:26
Update: The commit mentioned in the issue description led to the functional regression in FP8 training mentioned above. Upon reverting it, I observed that [another commit](https://github.com/openxla/xla/commit/e0a9a87787964e906d7b14c4953baa79b7a35e41) caused approximately a 10% performance regression. @reedwm, this is for your visibility.

cc @wenscarl, we need an automatic mechanism to capture similar issues in the future.

**Comment by kaixih** [comment] 2023-10-18 18:37
Let's focus on the functional regression commit for now.

I'd like to share the repro steps with you as I'm struggling to find available machines. If you happen to have the bandwidth, you can give this a try:
```bash
git clone https://github.com/kaixih/praxis.git 
git -C praxis/ checkout support-fp8-quantize-merged
 
git clone https://github.com/kaixih/paxml.git
git -C paxml/ checkout  overwrite-with-gradient-merged

pip install --no-deps -e praxis/
pip install --no-deps -e paxml/
```
Then, locate the launcher script run_pax_synthetic.sh at this link: https://gist.github.com/kaixih/ccd7d773353f7cbd0a417173217cc547

So, when the xla build contains this commit ID [f459e5777b49d5c34f4b27731fb1647728b5584a](https://github.com/openxla/xla/commit/f459e5777b49d5c34f4b27731fb1647728b5584a), run the following command:

```bash
bash run_pax_synthetic.sh fp8 
# you will encounter the above cublaslt error
```
To resolve the error, revert the commit using the following steps:

```bash
cd /opt/xla-source
git revert --no-edit f459e5777b49d5c34f4b27731fb1647728b5584a
# rebuild the xla
bash run_pax_synthetic.sh fp8 
# This should fix the issue.
```

**Comment by kaixih** [comment] 2023-10-18 19:57
I have obtained the XLA dump files and attached them here. Essentially, three experiments were conducted:

- **ref:** This version has no culprit commits and functions correctly with good performance.
- **ref+perf:** This includes [the performance regression commit](https://github.com/openxla/xla/commit/e0a9a87787964e906d7b14c4953baa79b7a35e41), causing it to function, but with slower performance.
- **ref+perf+func:** This includes both [functional](https://github.com/openxla/xla/commit/f459e5777b49d5c34f4b27731fb1647728b5584a) and performance regression commits and results in errors.

A quick comparison reveals that all the `before_optimizations` files are essentially the same, as expected. `ref+perf` differs significantly from `ref`, indicating that the performance commit optimizes the graph differently. `ref+perf+func` is essentially the same as `ref+perf`, as anticipated, since the functional commit involves only API cleanup and shouldn't alter the graph.

@reedwm and @akuegel for opinions.

[ref+perf+func_module_0025.pjit__wrapped_step_fn.before_optimizations.txt](https://github.com/openxla/xla/files/13033342/ref%2Bperf%2Bfunc_module_0025.pjit__wrapped_step_fn.before_optimizations.txt)
[ref+perf+func_module_0025.pjit__wrapped_step_fn.sm_9.0_gpu_after_optimizations.txt](https://github.com/openxla/xla/files/13033343/ref%2Bperf%2Bfunc_module_0025.pjit__wrapped_step_fn.sm_9.0_gpu_after_optimizations.txt)
[ref+perf_module_0025.pjit__wrapped_step_fn.before_optimizations.txt](https://github.com/openxla/xla/files/13033344/ref%2Bperf_module_0025.pjit__wrapped_step_fn.before_optimizations.txt)
[ref+perf_module_0025.pjit__wrapped_step_fn.sm_9.0_gpu_after_optimizations.txt](https://github.com/openxla/xla/files/13033345/ref%2Bperf_module_0025.pjit__wrapped_step_fn.sm_9.0_gpu_after_optimizations.txt)
[ref_module_0025.pjit__wrapped_step_fn.before_optimizations.txt](https://github.com/openxla/xla/files/13033346/ref_module_0025.pjit__wrapped_step_fn.before_optimizations.txt)
[ref_module_0025.pjit__wrapped_step_fn.sm_9.0_gpu_after_optimizations.txt](https://github.com/openxla/xla/files/13033347/ref_module_0025.pjit__wrapped_step_fn.sm_9.0_gpu_after_optimizations.txt)

**Comment by kaixih** [comment] 2023-10-23 23:48
Here's an update: Today I experimented with the latest XLA version (10-23) and found that reverting each of the two commits has become more complicated, as it now involves conflict resolution—a step that wasn't necessary last week. Given this development, I strongly believe we should prioritize resolving this issue promptly. If we delay, it might become even more challenging to address later on. 

@reedwm, I recall you mentioning that you would work on this. Could you kindly share your opinion on the matter? Additionally, if there's any way we can assist in resolving this, please let us know.

**Comment by kaixih** [comment] 2023-10-23 23:59
@jreiffers Regarding [this commit](https://github.com/openxla/xla/commit/e0a9a87787964e906d7b14c4953baa79b7a35e41), is there an XLA flag to disable it, or could you advise on the minimal change we can make to disable it, such as setting a certain branch to false? This would greatly aid us in debugging. Thank you.

**Comment by nouiz** [comment] 2023-10-24 14:35
If there isn't a flag, should we revert the bad commit?

**Comment by kaixih** [comment] 2023-10-24 18:54
Regarding the performance regression caused by [this commit](https://github.com/openxla/xla/commit/e0a9a87787964e906d7b14c4953baa79b7a35e41), I discovered that it was not due to the "priority fusion" but rather the associated changes in the GPU performance model. Specifically, setting [this 'coalesced'](https://github.com/openxla/xla/blob/a9e088e563c9e9ce7b8d00b15711f15063fceb38/xla/service/gpu/model/gpu_performance_model.cc#L359-L360) to true when calling `ReadTime()` resolved the performance issue. It's important to note that this doesn't mean we should always set 'coalesced' to true. For example, there is [another call](https://github.com/openxla/xla/blob/a9e088e563c9e9ce7b8d00b15711f15063fceb38/xla/service/gpu/model/gpu_performance_model.cc#L437-L440) to `ReadTime()` where the 'coalesced' argument should remain as it is currently.

cc. @reedwm

**Comment by kaixih** [comment] 2023-10-26 00:56
This boolean variable implies that if either the producer or the consumer involves a transpose operation, this `coalesced` will be `false`. However, is this statement accurate given the option to use tiled algorithms for transpose? @reedwm can you please reach out to the relevant colleagues for their comments on this matter? Thank you.
```
    bool coalesced = (fusion_analysis &&
                     fusion_analysis->GetEmitterFusionKind() ==
                          HloFusionAnalysis::EmitterFusionKind::kTranspose) ||
                     (!producer_transposes && !consumer_transposes);
```

**Comment by reedwm** [comment] 2023-10-26 01:41
> This boolean variable implies that if either the producer or the consumer involves a transpose operation, this `coalesced` will be `false`. However, is this statement accurate given the option to use tiled algorithms for transpose? @reedwm can you please reach out to the relevant colleagues for their comments on this matter? Thank you.
> 
> ```
>     bool coalesced = (fusion_analysis &&
>                      fusion_analysis->GetEmitterFusionKind() ==
>                           HloFusionAnalysis::EmitterFusionKind::kTranspose) ||
>                      (!producer_transposes && !consumer_transposes);
> ```

@jreiffers do you know why e0a9a87787964e906d7b14c4953baa79b7a35e41 would cause a regression here and why setting the `coalesced` variable to true would fix it?

**Comment by jreiffers** [comment] 2023-10-26 07:12
I'm sorry for the performance regression. This coalescing analysis is very crude, but it looked like an overall improvement in our benchmark suite.

The regression is likely caused by a missed fusion in FusionMerger. If you could extract the HLO before that pass and the HLO after that pass before the change, I'd be happy to take a look. Re: tiled emitter: the intention was to handle this through a check for the emitter kind. Judging from the issue title, I'm guessing we should be handling cuBLASLt there as well?

**Comment by kaixih** [comment] 2023-10-26 07:17
@jreiffers Thanks for the feedback. Can you check the HLO files from [this comment](https://github.com/openxla/xla/issues/6370#issuecomment-1769227168). Basically, the interesting ones are `ref` vs `ref+perf`, meaning the good one and bad one.

**Comment by jreiffers** [comment] 2023-10-26 08:16
Do you have a smaller reproducer? Finding a problematic fusion in a 1.6 MB HLO dump without a profile is probably not going to work.

**Comment by kaixih** [comment] 2023-10-26 23:09
@jreiffers Finding a smaller reproducer is a bit challenging because I really don't know what triggered the above perf issue, but I managed to narrow down the issue by restricting the transformer layer to just one, and then generating the hlo file. By utilizing the `interactive_graphviz` tool to inspect subgraphs, I stumbled upon something intriguing. 

I denote the current version as the **bad** version. For comparison, I also have a **good** version, where I replaced [this line](https://github.com/openxla/xla/blob/5bd1d9418778c60634c9c388f9b8f8001f73c202/xla/service/gpu/model/gpu_performance_model.cc#L344) with `bool coalesced = true;`

For the **good** version, this change resulted in a single fusion block, represented visually as follows:
![image](https://github.com/openxla/xla/assets/4001424/a280f777-f130-45a8-8331-dc0ce16ffaae)

For the **bad** version, the fusion block was split into two distinct blocks, illustrated below::
![image](https://github.com/openxla/xla/assets/4001424/95b1c3c8-1a88-4a06-845f-f96000271274)

![image](https://github.com/openxla/xla/assets/4001424/bebcb2ed-15fc-40dc-b6ae-cb51ef2b78d5)

To generate these subgraphs, you can refer to the provided HLO text and employ the `interactive_graphviz` tool. 

[bad.module_0025.pjit__wrapped_step_fn.before_optimizations.txt](https://github.com/openxla/xla/files/13183504/bad.module_0025.pjit__wrapped_step_fn.before_optimizations.txt)
[bad.module_0025.pjit__wrapped_step_fn.sm_9.0_gpu_after_optimizations.txt](https://github.com/openxla/xla/files/13183505/bad.module_0025.pjit__wrapped_step_fn.sm_9.0_gpu_after_optimizations.txt)
[good.module_0025.pjit__wrapped_step_fn.before_optimizations.txt](https://github.com/openxla/xla/files/13183537/good.module_0025.pjit__wrapped_step_fn.before_optimizations.txt)
[good.module_0025.pjit__wrapped_step_fn.sm_9.0_gpu_after_optimizations.txt](https://github.com/openxla/xla/files/13183538/good.module_0025.pjit__wrapped_step_fn.sm_9.0_gpu_after_optimizations.txt)

**Comment by jreiffers** [comment] 2023-10-27 11:58
Thanks! I believe I have a fix for this, currently running it through our benchmarks.

**Comment by kaixih** [comment] 2023-10-27 20:23
@jreiffers I attempted to rebuild XLA with the latest changes; however, the performance did not improve as expected. To regain the desired level of performance, I found it still necessary to set `bool coalesced = true;` in the function of `ProducerInputAccessTime`.

**Comment by kaixih** [comment] 2023-10-27 21:30
I confirmed that that subgraphs are still like the previous [figure](https://github.com/openxla/xla/issues/6370#issuecomment-1782034730). You can check these two attached files (change them to html before open).

[bad_two_fusions.html.txt](https://github.com/openxla/xla/files/13193459/bad_two_fusions.html.txt)
[good_one_fusion.html.txt](https://github.com/openxla/xla/files/13193455/good_one_fusion.html.txt)

**Comment by jreiffers** [comment] 2023-10-30 08:06
Sorry abut that. I'm not sure what's happening, disabling the coalescing analysis for now in https://github.com/openxla/xla/pull/6622.

**Closed** 2023-10-30 09:54 UTC
