### ISSUE TITLE
How can we use tf.print in tensorflow XLA

### ISSUE THREAD

**Issue by dathudeptrai** [openxla/xla#6623] opened 2023-10-30 08:31 UTC
The ability to debug in XLA mode is very important. Sometimes, without `jit_compile` everything worked as expect but with `jit_compile` the results just completely different. Is this possible today that we can debug XLA program in Tensorflow ?

**Comment by cheshire** [comment] 2023-10-31 07:30
I think that's a TF->XLA bridge question, so TF GH would be a more appropriate venue.

**Comment by dathudeptrai** [comment] 2023-10-31 07:31
@cheshire yeah, but they will take forever to reply us (classic :( )

**Comment by jcai19** [comment] 2023-10-31 20:26
@dathudeptrai Hi, do you have any reproducers?

**Comment by dathudeptrai** [comment] 2023-11-01 14:55
@jcai19 I think it is simple:

`
@tf.function(jit_compile=True)
def test_print(x):
    tf.print("hello world", x)

test_print(tf.constant(1.0))
`

**Comment by dathudeptrai** [comment] 2023-11-04 04:56
@jcai19 Thank you a lot. I think it is very important to have the ability to debug TF XLA :).

**Comment by penpornk** [comment] 2024-02-29 04:25
Closing this issue since the question is answered. Please feel free to reopen if this is not the case.

**Closed by penpornk** 2024-02-29 04:25 UTC
Labels: question
